// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HfgsTKFdzGMRshsYgBWimG8K9XtWrZw',
    appId: '1:195673986340:android:be254a19f6c7af2c7c0fb1',
    messagingSenderId: '195673986340',
    projectId: 'wayflutter-8410d',
    databaseURL: 'https://wayflutter-8410d-default-rtdb.firebaseio.com',
    storageBucket: 'wayflutter-8410d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjB386rQkFc1roS-z7RpKAcU33XUuyYtE',
    appId: '1:195673986340:ios:3318a9d87e53430b7c0fb1',
    messagingSenderId: '195673986340',
    projectId: 'wayflutter-8410d',
    databaseURL: 'https://wayflutter-8410d-default-rtdb.firebaseio.com',
    storageBucket: 'wayflutter-8410d.appspot.com',
    iosBundleId: 'app.ealaauser.com.ealaaUserr',
  );
}
